import React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      
    </div>
  )
}
